export const METAMASK_STATUSES = {
  NOT_INSTALLED: 'NOT_INSTALLED',
  NOT_CONNECTED: 'NOT_CONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  SIGNED_IN: 'SIGNED_IN',
} as const;

export const METAMASK_MESSAGES = {
  NOT_INSTALLED: 'NOT_INSTALLED',
  NOT_CONNECTED: 'NOT_CONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  USER_REJECTED_THE_REQUEST: 'USER_REJECTED_THE_REQUEST',

  IN_METAMASK_MAIN_NET: 'IN_METAMASK_MAIN_NET',
  NOT_IN_METAMASK_MAIN_NET: 'NOT_IN_METAMASK_MAIN_NET',
};

export const METAMASK_ERRORS = {
  USER_REJECTED_THE_REQUEST: 'USER_REJECTED_THE_REQUEST',
  USER_REQUEST_IS_ALREADY_PENDING: 'USER_REQUEST_IS_ALREADY_PENDING',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;
